version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    labels:
      - "dependencies"
      - "github-actions"
      - "major-update"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    labels:
      - "dependencies"
      - "docker"
      - "major-update"

