repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-symlinks
      - id: detect-private-key
        exclude: ^tests?/
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
          - post-commit

